// Generated by CoffeeScript 1.4.0
(function() {
  var child;

  child = {
    init: function(domain) {
      var p;
      p = this;
      p.prevHt = 0;
      p.modals = [];
      p.pm = new window.PostMsg(domain, true, 500);
      p.receive();
      p.send();
    },
    oHeight: function() {
      return document.body.offsetHeight;
    },
    setModal: function(elem) {
      var p;
      p = this;
      if (p.modals.indexOf(elem) === -1) {
        p.modals.push(elem);
      }
      p.positionModals(p.currentData);
    },
    positionModals: function(data) {
      var modal, _i, _len, _ref;
      if (!data) {
        return;
      }
      _ref = this.modals;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        modal = _ref[_i];
        this.calcModal(modal, data);
      }
    },
    calcModal: function(modal, data) {
      var documentCheck, fullHt, ht, marginTop, offsetHeight, p, top;
      p = this;
      ht = modal.height();
      fullHt = modal.outerHeight();
      offsetHeight = p.oHeight();
      documentCheck = data.docHt - data.scrollTop > offsetHeight ? data.offsetTop : 10;
      if ((data.top + data.scrollTop + documentCheck) > offsetHeight) {
        top = offsetHeight - fullHt - 10;
        marginTop = 0;
      } else if ((data.top * 2) - fullHt < (data.offsetTop * 2) && data.scrollTop < data.offsetTop) {
        top = 10;
        marginTop = 0;
      } else {
        top = data.top;
        marginTop = data.scrollTop - (fullHt / 2) - data.offsetTop;
      }
      modal.animate({
        top: top,
        marginTop: marginTop
      }, {
        duration: 250,
        queue: false
      });
    },
    receive: function() {
      var p;
      p = this;
      p.pm.on('receive', function(data) {
        p.currentData = data;
        p.positionModals(data);
      });
    },
    send: function() {
      var p;
      p = this;
      p.pm.bind(function() {
        var ht, obj;
        ht = p.oHeight();
        if (ht === p.prevHt) {
          return;
        }
        obj = {
          ht: ht
        };
        this.send(obj);
        p.prevHt = +ht;
      });
    }
  };

  child.init('http://bdev:8002');

  child.setModal($('#childModal'));

}).call(this);
