// Generated by CoffeeScript 1.4.0
(function() {
  var child;

  child = {
    init: function() {
      var p;
      p = this;
      p.prevHt = 0;
      p.modal = $('#childModal');
      p.pm = new window.PostMsg('http://bdev:8002', true, 500);
      p.receive();
      p.send();
    },
    calcModal: function(data) {
      var bottom, ht, marginTop, method, p, top;
      p = this;
      ht = p.modal.height();
      top = (data.top + data.scrollTop + (ht / 2)) > document.body.offsetHeight ? 'auto' : data.top;
      bottom = top !== 'auto' ? 'auto' : 10;
      marginTop = top !== 'auto' ? data.scrollTop - (ht / 2) - data.offsetTop : 0;
      method = bottom === 'auto' ? 'animate' : 'css';
      p.modal[method]({
        top: top,
        bottom: bottom,
        marginTop: marginTop
      }, 150);
    },
    receive: function() {
      var p;
      p = this;
      p.pm.on('receive', function(data) {
        p.calcModal(data);
      });
    },
    send: function() {
      var p;
      p = this;
      p.pm.bind(function() {
        var ht, obj;
        ht = document.body.offsetHeight;
        if (ht === p.prevHt) {
          return;
        }
        obj = {
          ht: ht
        };
        this.send(obj);
        p.prevHt = +ht;
      });
    }
  };

  child.init();

}).call(this);
