// Generated by CoffeeScript 1.4.0
(function() {
  var child;

  child = {
    init: function() {
      var p;
      p = this;
      p.prevHt = 0;
      p.modal = $('#childModal');
      p.pm = new window.PostMsg('http://bdev:8002', true, 500);
      p.receive();
      p.send();
    },
    calcModal: function(data) {
      var bottom, fullHt, ht, marginTop, method, p, top;
      p = this;
      ht = p.modal.height();
      fullHt = p.modal.outerHeight();
      if ((data.top + data.scrollTop) > document.body.offsetHeight) {
        top = 'auto';
        bottom = 10;
        marginTop = 0;
        method = 'css';
      } else if ((data.top * 2) - fullHt < (data.offsetTop * 2) && data.scrollTop < data.offsetTop) {
        top = 10;
        bottom = 'auto';
        marginTop = 0;
        method = 'css';
      } else {
        top = data.top;
        bottom = 'auto';
        marginTop = data.scrollTop - (fullHt / 2) - data.offsetTop;
        method = 'animate';
      }
      p.modal[method]({
        top: top,
        bottom: bottom,
        marginTop: marginTop
      }, {
        duration: 250,
        queue: false
      });
    },
    receive: function() {
      var p;
      p = this;
      p.pm.on('receive', function(data) {
        p.calcModal(data);
      });
    },
    send: function() {
      var p;
      p = this;
      p.pm.bind(function() {
        var ht, obj;
        ht = document.body.offsetHeight;
        if (ht === p.prevHt) {
          return;
        }
        obj = {
          ht: ht
        };
        this.send(obj);
        p.prevHt = +ht;
      });
    }
  };

  child.init();

}).call(this);
