// Generated by CoffeeScript 1.4.0
(function() {
  var num, pm;

  pm = new window.PostMsg('http://bdev:8002', false, 500);

  num = 0;

  pm.once('receive', function(data) {
    return pm.bind(function() {
      var obj;
      obj = {
        hello: 'child'
      };
      this.send(data._source, obj);
      return this.unbind(this.id);
    });
  });

  pm.on('receive', function(data, id) {
    console.log(data);
    return pm.off('receive', id);
  });

}).call(this);
