// Generated by CoffeeScript 1.4.0
(function() {
  var pm;

  pm = new window.PostMsg('http://bdev:8002');

  pm.on('receive', function(e, data) {
    var obj;
    console.log(data);
    obj = {
      hello: 'child'
    };
    return data.postmsg.send(data._source, JSON.stringify(obj));
  });

  pm.bind(function() {});

}).call(this);
