// Generated by CoffeeScript 1.4.0
(function() {
  var ifr, modal, num, pm;

  pm = new window.PostMsg('http://bdev:8002', false, 500);

  num = 0;

  ifr = $('iframe');

  modal = $('#parentModal');

  pm.on('receive', function(data, id) {
    ifr[0].scrolling = 'no';
    ifr.height(data.ht);
  });

  $(window).on('scroll', function(e) {
    modal.css('top', this.innerHeight / 2);
    return modal.css('marginTop', window.scrollY - modal.height() / 2);
  });

}).call(this);
